// GET: read-only venue list, reassembled from D1's `venues` table (see
// migrations/005_venues.sql) into the shape data/venues.json used to
// produce back when it was the source of truth — js/app.js and
// functions/api/checkin.js both read live from D1 now (this endpoint and a
// direct query respectively); data/venues.json is a mirror, regenerated by
// scripts/export-venues.js.
//
// POST: an owner submitting a brand-new venue ("List your venue" on the
// flame sheet, js/app.js openVenueSubmitForm()). Inserts with pin_status
// 'pending' and lat/lng NULL — there is no map pin until Kar looks at the
// submitted Google Maps link and sets real coordinates by hand (see
// functions/api/pending.js and migrations/009_pin_status.sql). No lat/lng
// input exists anywhere in this request; the server never accepts
// coordinates from an owner, submitting or editing.
//
// venuesFallback is bundled into the Function at build time (see the 2026-08
// outage where a deploy referenced a column that didn't exist on production
// yet — every request 500'd with nothing to show). If the D1 query throws
// for any reason, we serve this mirror instead of an error so the app still
// has something on the map; the response is marked "stale" so the frontend
// can tell the user, and never cached, so the very next request tries D1
// fresh rather than being stuck on stale data for a Cache-Control window.
// The fallback only ever applies to GET — a POST during a D1 outage just
// fails, there's nothing sane to fall back to for a write.
import venuesFallback from '../../data/venues.json';
import { getSessionUser } from './_auth.js';
import { isAdmin } from './_admin.js';
import { readCheckinRadius } from './_checkin-config.js';
import {
  SIMPLE_FIELDS, REQUIRED_SIMPLE_FIELDS, VENUE_TYPES, MAX_LEN, isUrlish,
  validateHours, validateContact, validateParking, validateSignature,
} from './_venue-validation.js';

async function handleGet(context) {
  try {
    const db = context.env.DB;
    const cache = caches.default;
    const cacheKey = new Request(context.request.url, { method: 'GET' });

    const cached = await cache.match(cacheKey);
    if (cached) return cached;

    // 'rejected' (see functions/api/venues/[id]/reject.js) is deliberately
    // excluded here — a turned-down submission isn't deleted, but it also
    // shouldn't be publicly browsable. The owner still sees it via the
    // unfiltered /api/my-venues -> "Manage your venue" (js/app.js)
    const rows = await db.prepare(
      `SELECT id, name, short_name, name_lo, type, lat, lng, area, short,
              description, photos, hours, hours_note, contact, parking, links,
              verified, status, source, signature, pin_status, vibe, outdoor,
              why, rating, review_count
       FROM venues WHERE pin_status != 'rejected' ORDER BY rowid`
    ).all();

    /* Zero venues is treated as a failure, not as a result. This app has
       never had, and will never legitimately have, an empty venue table —
       but an empty result is exactly what a truncated table, a botched
       re-import or a query against the wrong database looks like. Served
       as-is it was also CACHED for an hour and adopted by every client over
       the bundled mirror, blanking the app with no error anywhere: the
       August-outage shape (a broken response indistinguishable from a real
       one). Throwing sends it down the same path as a D1 error: the
       bundled mirror, marked stale, never cached. js/app.js refuses an
       empty list too, so an older deploy of this file cannot cause it. */
    if (!rows.results.length) throw new Error('venues query returned no rows');

    // the check-in radius, from its one home (see _checkin-config.js), so the
    // client's "You're here" button uses the server's own number
    const checkinRadiusM = await readCheckinRadius(db);

    const venues = rows.results.map((r) => {
      const v = {
        id: r.id,
        name: r.name,
        short_name: r.short_name,
        name_lo: r.name_lo,
        type: r.type,
        lat: r.lat,
        lng: r.lng,
        area: r.area,
        short: r.short,
        description: r.description,
        photos: JSON.parse(r.photos || '[]'),
        hours: r.hours ? JSON.parse(r.hours) : null,
        hours_note: r.hours_note,
        links: r.links ? JSON.parse(r.links) : {},
        verified: !!r.verified,
        source: r.source,
        pin_status: r.pin_status,
      };
      // contact/parking/status are omitted entirely when absent, matching
      // data/venues.json's convention — never emitted as null
      if (r.contact !== null) v.contact = JSON.parse(r.contact);
      if (r.parking !== null) v.parking = JSON.parse(r.parking);
      if (r.status !== null) v.status = r.status;
      if (r.signature !== null) v.signature = JSON.parse(r.signature);
      if (r.vibe !== null) v.vibe = JSON.parse(r.vibe);
      // outdoor is tri-state and the third state is carried by ABSENCE, the
      // same convention contact/parking/status use above: 1 -> true, 0 ->
      // false, NULL -> field omitted entirely. It must not come through as
      // `false`, because the client's rain note distinguishes "we checked,
      // it's indoors" from "nobody has looked" — see outdoorNoteHtml() in
      // js/app.js and migrations/016_outdoor.sql.
      if (r.outdoor !== null) v.outdoor = !!r.outdoor;
      // why / rating / review_count (migrations/017_why_rating.sql) — omitted
      // when NULL, the same absence convention as the fields above. NULL for
      // every venue when 017 runs, so this payload (and the bundle
      // fingerprint js/app.js compares it against) is unchanged until Kar
      // sets one. rating is only meaningful with review_count > 0; the client
      // checks that itself rather than trusting the pair.
      if (r.why !== null) v.why = r.why;
      if (r.rating !== null) v.rating = r.rating;
      if (r.review_count !== null) v.review_count = r.review_count;
      return v;
    });

    const response = Response.json(
      { venues, checkin_radius_m: checkinRadiusM },
      // one hour, not five minutes: venue data changes weekly at most,
      // and every path that changes it purges this exact cache key
      // immediately afterwards — the POST below, and
      // functions/api/venues/[id].js, [id]/approve.js and [id]/reject.js —
      // so an owner's edit still appears at once rather than waiting the
      // TTL out. The TTL only governs how long a *stale-but-unedited*
      // response is reused, which is exactly where the round trip to D1
      // is pure cost.
      // s-maxage, not max-age. The edge copy (caches.default above) is the
      // one every write path purges; the BROWSER's own HTTP cache is not,
      // and max-age=3600 let it serve this response for an hour without
      // asking. So an owner who saved an edit and reloaded, or Kar
      // approving a pin, got their own pre-edit copy back from disk and saw
      // the change "not save". Measured locally: after a D1 edit and a
      // purge, a reload served /api/venues with transferSize 0 and the old
      // name. The Cache API honours s-maxage for the edge copy, so the hour
      // of D1 savings stays; max-age=0 makes browsers come back to the
      // edge each load, which is a cache hit there, not a D1 query.
      { headers: { 'Cache-Control': 'public, max-age=0, s-maxage=3600' } }
    );
    context.waitUntil(cache.put(cacheKey, response.clone()));
    return response;
  } catch (e) {
    // still logged so the real cause (e.g. a migration that never ran
    // against --remote) stays diagnosable — see CLAUDE.md's workflow rules
    console.error('venues fetch failed, serving bundled fallback:', e);
    return Response.json(
      { venues: venuesFallback.venues.filter(v => v.pin_status !== 'rejected'), stale: true },
      { headers: { 'Cache-Control': 'no-store' } }
    );
  }
}

function slugify(name) {
  const base = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 50);
  return base || 'venue';
}

// appends -2, -3, ... on collision — ids are short human-readable slugs
// (see existing venues in data/venues.json), not random, so two "Baron"
// submissions read as baron / baron-2, not a UUID soup
async function uniqueVenueId(db, name) {
  const base = slugify(name);
  let id = base;
  let n = 1;
  while (await db.prepare('SELECT 1 FROM venues WHERE id = ?').bind(id).first()) {
    n++;
    id = `${base}-${n}`;
  }
  return id;
}

// same field rules as validateSimpleFields in _venue-validation.js, but for
// a fresh row every SIMPLE_FIELD is being set at once (not a sparse PATCH),
// so this returns a plain {field: value} object instead of pushing
// "field = ?" pairs — name/area/type are required here in a way PATCH never
// requires them (PATCH only validates a field if it's present at all)
function validateCreateFields(body, errors) {
  const out = {};
  for (const field of SIMPLE_FIELDS) {
    const v = body[field];
    if (field === 'type') {
      if (!VENUE_TYPES.includes(v)) { errors.type = `must be one of: ${VENUE_TYPES.join(', ')}`; continue; }
      out.type = v;
      continue;
    }
    const trimmed = typeof v === 'string' ? v.trim() : '';
    if (REQUIRED_SIMPLE_FIELDS.has(field) && !trimmed) { errors[field] = `${field} can't be empty`; continue; }
    if (trimmed.length > MAX_LEN[field]) {
      errors[field] = `must be ${MAX_LEN[field]} characters or fewer`;
      continue;
    }
    out[field] = trimmed;
  }
  return out;
}

const MAX_PENDING_PER_OWNER = 3;

async function handlePost(context) {
  try {
    const user = await getSessionUser(context);
    if (!user) return Response.json({ ok: false, need_auth: true }, { status: 401 });

    /* One free account could submit without limit, and a pending venue is
       publicly listed (CLAUDE.md: it appears in list sections and type
       filters so the owner sees it went through) — so this was unlimited,
       unreviewed public text for anyone with a Google account. Capped at
       MAX_PENDING_PER_OWNER waiting at once; an approval or rejection frees
       a slot. The admin is exempt. The number is a judgement, not a
       measured need — see autonomous-run.md. It limits volume, not what a
       single submission says; that is the moderation question flagged
       there. */
    if (!isAdmin(context, user)) {
      const waiting = await context.env.DB.prepare(
        `SELECT COUNT(*) AS c FROM venue_owners o JOIN venues v ON v.id = o.venue_id
         WHERE o.user_id = ? AND v.pin_status = 'pending'`
      ).bind(user.id).first();
      if ((waiting?.c || 0) >= MAX_PENDING_PER_OWNER) {
        return Response.json({
          ok: false,
          error: `You already have ${MAX_PENDING_PER_OWNER} venues waiting for review — you can add another once one has been checked.`,
        }, { status: 429 });
      }
    }

    const body = await context.request.json().catch(() => null);
    if (!body || typeof body !== 'object') {
      return Response.json({ ok: false, error: 'invalid body' }, { status: 400 });
    }

    const errors = {};
    const fields = validateCreateFields(body, errors);

    // the one field the normal edit form doesn't require — no lat/lng
    // input exists anywhere, so this Maps link is the only lead Kar has to
    // go place the pin from (see functions/api/pending.js)
    const mapsUrl = typeof body.maps_url === 'string' ? body.maps_url.trim() : '';
    if (!mapsUrl) errors.maps_url = 'Google Maps link is required';
    else if (!/^https?:\/\/\S+$/i.test(mapsUrl)) errors.maps_url = "doesn't look like a link";

    const links = { maps: mapsUrl };
    if ('links' in body) {
      const l = body.links;
      if (typeof l !== 'object' || l === null || Array.isArray(l)) {
        errors.links = 'invalid links';
      } else {
        for (const key of ['facebook', 'website']) {
          if (!(key in l)) continue;
          const v = typeof l[key] === 'string' ? l[key].trim() : '';
          if (!isUrlish(v)) { errors.links = `${key} doesn't look like a link`; break; }
          links[key] = v;
        }
      }
    }

    const hours = validateHours(body.hours ?? null, errors);
    const contact = validateContact(body.contact ?? null, errors);
    const parking = validateParking(body.parking ?? null, errors);
    const signature = validateSignature(body.signature ?? null, errors);

    if (Object.keys(errors).length > 0) {
      return Response.json({ ok: false, errors }, { status: 400 });
    }

    const db = context.env.DB;
    const id = await uniqueVenueId(db, fields.name);
    const nowIso = new Date().toISOString();
    const source = `owner submission, ${nowIso.slice(0, 10)}`;

    await db.batch([
      db.prepare(
        `INSERT INTO venues (
           id, name, short_name, name_lo, type, lat, lng, area, short,
           description, photos, hours, hours_note, contact, parking, links, verified,
           status, source, updated_at, location_review, signature, pin_status
         ) VALUES (?, ?, ?, ?, ?, NULL, NULL, ?, ?, ?, '[]', ?, ?, ?, ?, ?, 0,
           NULL, ?, ?, 0, ?, 'pending')`
      ).bind(
        id, fields.name, fields.short_name || null, fields.name_lo || null,
        fields.type, fields.area || null, fields.short || null,
        fields.description || null,
        hours ? JSON.stringify(hours) : null,
        fields.hours_note || null,
        contact ? JSON.stringify(contact) : null,
        parking ? JSON.stringify(parking) : null,
        JSON.stringify(links),
        source, nowIso,
        signature ? JSON.stringify(signature) : null
      ),
      db.prepare(
        'INSERT INTO venue_owners (user_id, venue_id, granted_at) VALUES (?, ?, ?)'
      ).bind(user.id, id, nowIso),
    ]);

    // a pending venue is deliberately excluded from the public list's
    // renderMarkers/editorial sections, but it's still new data — purge so
    // it shows up in list sections/type filters right away (see
    // js/app.js renderHomeSheet) instead of waiting out the hour-long TTL
    const publicVenuesUrl = new URL('/api/venues', context.request.url).toString();
    await caches.default.delete(new Request(publicVenuesUrl, { method: 'GET' }));

    return Response.json({
      ok: true,
      venue: {
        id, name: fields.name, short_name: fields.short_name || null,
        name_lo: fields.name_lo || null, type: fields.type,
        lat: null, lng: null, area: fields.area || null,
        short: fields.short || null, description: fields.description || null,
        photos: [], hours: hours || null, hours_note: fields.hours_note || null, links, verified: false,
        source, pin_status: 'pending',
        ...(contact ? { contact } : {}),
        ...(parking ? { parking } : {}),
        ...(signature ? { signature } : {}),
      },
    });
  } catch (e) {
    console.error(e);
    return Response.json({ ok: false, error: 'submission failed' }, { status: 500 });
  }
}

export async function onRequest(context) {
  if (context.request.method === 'GET') return handleGet(context);
  if (context.request.method === 'POST') return handlePost(context);
  return Response.json({ ok: false, error: 'method not allowed' }, { status: 405 });
}
