// Read-only venue list, reassembled from D1's `venues` table (see
// migrations/005_venues.sql) into the shape data/venues.json used to
// produce back when it was the source of truth — js/app.js and
// functions/api/checkin.js both read live from D1 now (this endpoint and a
// direct query respectively); data/venues.json is a mirror, regenerated by
// scripts/export-venues.js.
export async function onRequest(context) {
  if (context.request.method !== 'GET') {
    return Response.json({ ok: false, error: 'method not allowed' }, { status: 405 });
  }

  try {
    const db = context.env.DB;
    const cache = caches.default;
    const cacheKey = new Request(context.request.url, { method: 'GET' });

    const cached = await cache.match(cacheKey);
    if (cached) return cached;

    const rows = await db.prepare(
      `SELECT id, name, short_name, name_lo, type, lat, lng, area, short,
              description, photos, hours, contact, parking, links,
              verified, status, source, signature
       FROM venues ORDER BY rowid`
    ).all();

    const venues = rows.results.map((r) => {
      const v = {
        id: r.id,
        name: r.name,
        short_name: r.short_name,
        name_lo: r.name_lo,
        type: r.type,
        lat: r.lat,
        lng: r.lng,
        area: r.area,
        short: r.short,
        description: r.description,
        photos: JSON.parse(r.photos || '[]'),
        hours: r.hours ? JSON.parse(r.hours) : null,
        links: r.links ? JSON.parse(r.links) : {},
        verified: !!r.verified,
        source: r.source,
      };
      // contact/parking/status are omitted entirely when absent, matching
      // data/venues.json's convention — never emitted as null
      if (r.contact !== null) v.contact = JSON.parse(r.contact);
      if (r.parking !== null) v.parking = JSON.parse(r.parking);
      if (r.status !== null) v.status = r.status;
      if (r.signature !== null) v.signature = JSON.parse(r.signature);
      return v;
    });

    const response = Response.json(
      { venues },
      { headers: { 'Cache-Control': 'public, max-age=300' } }
    );
    context.waitUntil(cache.put(cacheKey, response.clone()));
    return response;
  } catch (e) {
    console.error(e);
    return Response.json({ ok: false, error: 'venues fetch failed' }, { status: 500 });
  }
}
