#!/usr/bin/env node
// Enforces the data integrity rules CLAUDE.md states and nothing else checks.
// Reads the repo's data files and exits non-zero, listing every problem, if
// any rule is broken:
//
//   node scripts/check-data.js
//
// Read-only and offline: no network, no wrangler, no D1. That matters for
// what it can and cannot tell you. Venues live in D1, and data/venues.json
// is a MIRROR regenerated by scripts/export-venues.js — so this checks the
// venues as of the last export, not production right now. Run the export
// first if D1 has changed since (CLAUDE.md already asks for that after any
// D1 edit). Events and picks ARE their own source of truth, so for those
// this is checking the real thing.
//
// Deliberately never fixes anything. A rule failure means a person has to go
// and look — "verified with no source" is fixed by finding the source or
// un-verifying, never by typing a plausible-looking one in.
//
// The rules, and where each comes from in CLAUDE.md:
//   venues
//     V1  verified: true must carry a source ("owner confirms from a real
//         source")
//     V2  hours, when present, are an object of mon..sun, each null or a
//         valid "HH:MM-HH:MM" range (close may run to 27:59 for past-
//         midnight closing — the same rule functions/api/_venue-validation.js
//         applies to owner writes)
//     V3  a venue with status "opening-soon" has no hours (it is not open
//         yet, so any hours are a guess)
//     V4  every photo is a Cloudinary "v<digits>/<publicId>" reference
//         (cloudinaryUrl() in js/app.js) — never a full URL, which is how a
//         hotlinked or guessed image would arrive ("no photo > wrong photo")
//     V5  pin_status "placed" means real, Kar-confirmed lat/lng — never null
//     V6  pin_status "pending" means NO coordinates — never a placeholder
//     V7  ids are unique
//     V8  why, when present, is a non-empty string (absent = not written)
//     V9  rating, when present, is a number from 1 to 5; review_count, when
//         present, is a whole number >= 0
//     V10 rating and review_count > 0 come together — a rating with no
//         reviews of our own behind it came from somewhere else
//         (migrations/017_why_rating.sql: never an aggregator's rating)
//     V11 logo, when present, is a Cloudinary "v<digits>/<publicId>"
//         reference — the same shape as a photo (V4), since it is the same
//         kind of value and goes through the same cloudinaryUrl(). Absent =
//         no logo, which is the normal case and not a problem
//         (migrations/018_logo.sql)
//   events
//     E1  every event has a source_url
//     E2  venue_id is null or the id of a venue that exists
//     E3  photo, when present, has the same shape as V4
//     E4  ids are unique
//   picks
//     P1  every id in venue_ids / busy_venue_ids is a venue that exists

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const read = (f) => JSON.parse(fs.readFileSync(path.join(ROOT, 'data', f), 'utf8'));

// the "v<digits>/<publicId>" shape cloudinaryUrl() in js/app.js expects
// (CLOUDINARY_STORED_RE there is /^v\d+\/.+$/). Slightly stricter: no
// whitespace, "?" or "#", which no real public ID contains and a pasted URL
// fragment would. Dots ARE allowed — real IDs have them ("mahasan.bar_x77hwf"),
// and a first draft of this rule that forbade them flagged five good photos.
const PHOTO_RE = /^v\d+\/[^\s?#]+$/;
const DAYS = ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'];
// same rule as validHourRange() in functions/api/_venue-validation.js
function validHourRange(str) {
  const m = /^(\d{2}):(\d{2})-(\d{2}):(\d{2})$/.exec(str);
  if (!m) return false;
  const [, oh, om, ch, cm] = m.map(Number);
  if (oh > 23 || om > 59 || ch > 27 || cm > 59) return false;
  return ch * 60 + cm > oh * 60 + om;
}

const problems = [];
const fail = (rule, where, msg) => problems.push({ rule, where, msg });

const { venues } = read('venues.json');
const { events } = read('events.json');
const picks = read('picks.json');

const venueIds = new Set();
for (const v of venues) {
  const where = `venue ${v.id}`;
  if (venueIds.has(v.id)) fail('V7', where, 'duplicate id');
  venueIds.add(v.id);

  if (v.verified === true && !(typeof v.source === 'string' && v.source.trim())) {
    fail('V1', where, 'verified: true but no source');
  }

  if (v.hours !== null && v.hours !== undefined) {
    if (typeof v.hours !== 'object' || Array.isArray(v.hours)) {
      fail('V2', where, 'hours is not an object');
    } else {
      for (const k of Object.keys(v.hours)) {
        if (!DAYS.includes(k)) fail('V2', where, `hours has unknown day "${k}"`);
      }
      for (const d of DAYS) {
        const h = v.hours[d];
        if (h === null || h === undefined) continue;
        if (typeof h !== 'string' || !validHourRange(h)) fail('V2', where, `hours.${d} "${h}" is not a valid HH:MM-HH:MM range`);
      }
    }
    if (v.status === 'opening-soon') {
      const anyHours = typeof v.hours === 'object' && DAYS.some((d) => v.hours[d]);
      if (anyHours) fail('V3', where, 'status "opening-soon" but has hours');
    }
  }

  for (const p of v.photos || []) {
    if (typeof p !== 'string' || !PHOTO_RE.test(p)) fail('V4', where, `photo "${p}" is not a "v<digits>/<publicId>" reference`);
  }

  const hasCoords = v.lat !== null && v.lat !== undefined && v.lng !== null && v.lng !== undefined;
  if (v.pin_status === 'placed' && !hasCoords) fail('V5', where, 'pin_status "placed" but lat/lng are null');
  if (v.pin_status === 'pending' && (v.lat != null || v.lng != null)) fail('V6', where, 'pin_status "pending" but has coordinates');

  if ('why' in v && !(typeof v.why === 'string' && v.why.trim())) fail('V8', where, 'why is present but not a non-empty string (omit it instead)');
  if ('rating' in v && !(typeof v.rating === 'number' && v.rating >= 1 && v.rating <= 5)) fail('V9', where, `rating ${JSON.stringify(v.rating)} is not a number from 1 to 5`);
  if ('review_count' in v && !(Number.isInteger(v.review_count) && v.review_count >= 0)) fail('V9', where, `review_count ${JSON.stringify(v.review_count)} is not a whole number >= 0`);
  const reviewed = Number.isInteger(v.review_count) && v.review_count > 0;
  if ('rating' in v && !reviewed) fail('V10', where, 'rating with no review_count > 0 — a rating must come from Paisaidee\'s own reviews');
  if (reviewed && !('rating' in v)) fail('V10', where, 'review_count > 0 but no rating');

  // same shape as a photo (V4) — a logo goes through the same
  // cloudinaryUrl(), so a full URL pasted in here fails for the same reason
  if ('logo' in v && !(typeof v.logo === 'string' && PHOTO_RE.test(v.logo))) {
    fail('V11', where, `logo "${v.logo}" is not a "v<digits>/<publicId>" reference`);
  }
}

const eventIds = new Set();
for (const ev of events) {
  const where = `event ${ev.id}`;
  if (eventIds.has(ev.id)) fail('E4', where, 'duplicate id');
  eventIds.add(ev.id);
  if (!(typeof ev.source_url === 'string' && ev.source_url.trim())) fail('E1', where, 'no source_url');
  if (ev.venue_id !== null && ev.venue_id !== undefined && !venueIds.has(ev.venue_id)) {
    fail('E2', where, `venue_id "${ev.venue_id}" does not exist`);
  }
  if (ev.photo !== undefined && ev.photo !== null && !(typeof ev.photo === 'string' && PHOTO_RE.test(ev.photo))) {
    fail('E3', where, `photo "${ev.photo}" is not a "v<digits>/<publicId>" reference`);
  }
}

for (const key of ['venue_ids', 'busy_venue_ids']) {
  for (const id of picks[key] || []) {
    if (!venueIds.has(id)) fail('P1', `picks.${key}`, `"${id}" does not exist`);
  }
}

if (problems.length) {
  console.error(`check-data: ${problems.length} problem${problems.length === 1 ? '' : 's'}\n`);
  for (const p of problems) console.error(`  [${p.rule}] ${p.where}: ${p.msg}`);
  console.error('\nNothing was changed. Fix each by finding the real value, never by guessing one.');
  process.exit(1);
}
console.log(`check-data: OK — ${venues.length} venues, ${events.length} events, picks`);
